# PR02_Demonstration of Data Cleaning and Manipulation with Pandas

### Import Pandas and load data ###

In [1]:
import pandas as pd
import numpy as np

In [2]:
# encoding option to deal with files in different formats
df = pd.read_csv('input/attacks.csv', encoding='ISO-8859-1')
df.head(5)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

### Exploration of the original DataFrame ###

In [3]:
# dimension
df.shape

(25723, 24)

In [4]:
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

### Cleaning Text and Data Type Correction###

Premise: I'll cleaning only the columns that I'll use in my analysis:
[case_number, date, year, type, country, area, activity, sex, injury, fatal (y/n)]

In [5]:
# data type
df.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order            float64
Unnamed: 22                object
Unnamed: 23                object
dtype: object

In [6]:
# COLUMN'S NAMES
# making changes at the column's names: deleting white spaces/ lowercases
df.columns = df.columns.to_series().apply(lambda x: x.strip().lower())
df.columns

Index(['case number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal (y/n)', 'time',
       'species', 'investigator or source', 'pdf', 'href formula', 'href',
       'case number.1', 'case number.2', 'original order', 'unnamed: 22',
       'unnamed: 23'],
      dtype='object')

In [7]:
# CASE NUMBER
# rename 'case number column' to elimnate white spaces
df.rename(columns={'case number':'case_number'}, inplace=True)

In [8]:
# eliminate 
df[(df['case_number'] == '1909.06.26.a.R') | (df['case_number'] == '1895.11.21.R')]
#data[(data['rnd_2'] == 2) & (data['rnd_3'] > 15)]]

,case_number,date,year,type,country,area,location,activity,name,sex,...,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order,unnamed: 22,unnamed: 23
5418,1909.06.26.a.R,Reported 26-Jun-1909,1909.0,Unprovoked,MEXICO,Guerrero,Zacatula,Bathing,Rosa Lopez,F,...,NaN,"Adams County News, 6/26/1909",1909.06.26.a.R-Lopez.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1909.06.26.a.R,1909.06.26.a.R,885.0,NaN,NaN
5628,1895.11.21.R,Reported 21-Nov-1895,1895.0,Unprovoked,BARBADOS,St Michael Parish,Bridgetown,Diving for coins,Rouee Youma,M,...,NaN,"NY Times, 11/21/1895",1895.11.21.R-Youma.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1895.11.21.R,1895.11.21.R,675.0,NaN,NaN

In [9]:
# making changes to the 'country' column 
df['country'].str.replace('?','').str.replace(' / ','/').str.upper().unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'NEW CALEDONIA',
       'ECUADOR', 'MALAYSIA', 'LIBYA', nan, 'CUBA', 'MAURITIUS',
       'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS', 'JAPAN',
       'EGYPT', 'ST HELENA, BRITISH OVERSEAS TERRITORY', 'COMOROS',
       'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'FIJI', 'DOMINICAN REPUBLIC',
       'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'PUERTO RICO', 'ITALY',
       'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'SIERRA LEONE', 'ST. MAARTIN',
       'GRAND CAYMAN', 'LIBERIA', 'VANUATU', 'MEXICO ', 'HONDURAS',
       'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY', 'INDIA',
       'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA',
       'MARSHALL ISLANDS', 'EGYPT/ISRAEL', 'NORTHERN ARABIAN SEA',
       'HONG KONG', 'EL SALVADOR', 'ANGOLA', 'BERMUDA', 'MONTENEGRO',
       'IRAN', 'TUNISIA', 'NAMIBIA', 'NORTH ATLANTIC OCEAN', 'PORTUGAL',
       'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
       'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
       'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
       'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
       'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'MID ATLANTIC OCEAN', 'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'RED SEA/INDIAN OCEAN',
       'PACIFIC OCEAN', 'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS',
       'AMERICAN SAMOA', 'ANDAMAN/NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
       'NORTH ATLANTIC OCEAN ', 'THE BALKANS', 'ARGENTINA', 'MARTINIQUE',
       'INDIAN OCEAN', 'GUATEMALA', 'NETHERLANDS ANTILLES',
       'NORTHERN MARIANA ISLANDS', 'IRAN/IRAQ', 'JAVA', ' PHILIPPINES',
       'NICARAGUA', 'CENTRAL PACIFIC', 'SOLOMON ISLANDS/VANUATU',
       'SOUTHWEST PACIFIC OCEAN', 'BAY OF BENGAL', 'MID-PACIFC OCEAN',
       'SLOVENIA', 'CURACAO', 'ICELAND', 'ITALY/CROATIA', 'BARBADOS',
       'MONACO', 'GUYANA', 'HAITI', 'SAN DOMINGO', 'IRELAND', 'KUWAIT',
       'YEMEN ', 'REUNION ISLAND', 'FALKLAND ISLANDS', 'CRETE', 'CYPRUS',
       'EGYPT ', 'WEST INDIES', 'BURMA', 'LEBANON', 'PARAGUAY',
       'BRITISH NEW GUINEA', 'CEYLON', 'OCEAN', 'GEORGIA', 'SYRIA',
       'TUVALU', 'GUINEA', 'ANDAMAN ISLANDS',
       'EQUATORIAL GUINEA/CAMEROON', 'COOK ISLANDS', 'TOBAGO', 'PERU',
       'AFRICA', 'ALGERIA', 'COAST OF AFRICA', 'TASMAN SEA', 'GHANA',
       'GREENLAND', 'MEDITERRANEAN SEA', 'SWEDEN', 'ROATAN',
       'BETWEEN PORTUGAL & INDIA', 'DJIBOUTI', 'BAHREIN', 'KOREA', 'ASIA',
       'CEYLON (SRI LANKA)'], dtype=object)

### Drop all empy rows ###

In [10]:
# drop all the empty rows
df = df.dropna(how = 'all')
# df.head(5)

In [11]:
df.shape

(8703, 24)

In [12]:
# 'case number' list
# cn_list = df['case_number'].tolist()
# cn =set(cn_list)
# # print(cn)

# for row in df['case_number']:
#     while True:
#         if row != 0:
#             continue
#         else:
#             print(f'Empty list!')
#             break

In [13]:
# all thes columns can be eliminated because contain irrilevant data ('case number==0')
df[df['case_number']=='0']

,case_number,date,year,type,country,area,location,activity,name,sex,...,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order,unnamed: 22,unnamed: 23
6302,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6304.0,NaN,NaN
6303,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6305.0,NaN,NaN
6304,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6306.0,NaN,NaN
6305,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6307.0,NaN,NaN
6306,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6308.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8697,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# hp: keeping all the rows with at least 14 No Nan values
df = df.dropna(thresh =14)
df.head(5)

,case_number,date,year,type,country,area,location,activity,name,sex,...,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order,unnamed: 22,unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [15]:
df.shape

(6302, 24)

### Searching for duplicate rows ###

In [16]:
# searching duplicates in the column'Case Number'
df['case_number'].duplicated().value_counts()

False    6286
True       16
Name: case_number, dtype: int64

In [17]:
duplicates = df[df['case_number'].duplicated(keep=False)].count()
duplicates

case_number               32
date                      32
year                      32
type                      32
country                   32
area                      29
location                  32
activity                  27
name                      30
sex                       31
age                       15
injury                    32
fatal (y/n)               27
time                      11
species                   17
investigator or source    32
pdf                       32
href formula              32
href                      32
case number.1             32
case number.2             32
original order            32
unnamed: 22                0
unnamed: 23                0
dtype: int64

In [91]:
#drop all duplicates considering selected columns
# select_columns=['case_number','date','year','type','country','location','injury']
df.drop_duplicates(subset= df.columns, inplace = True)
df.head(5)

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,"No injury to occupant, outrigger canoe and pad...",N,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,Minor injury to left thigh,N,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,Injury to left lower leg from surfboard skeg,N,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,Minor injury to lower leg,N,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,Lacerations to leg & hand shark PROVOKED INCIDENT,N,A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299

In [19]:
df.shape

(6302, 24)

In [92]:
# DOESN'T WORK! WHY?
df['case_number'].duplicated().sum()

8

### Missing Values ###

In [21]:
# number of nulls/columns --> Remove!
nulls_cols = df.isnull().sum()
nulls_cols

case_number                  1
date                         0
year                         2
type                         4
country                     50
area                       455
location                   540
activity                   544
name                       210
sex                        565
age                       2831
injury                      28
fatal (y/n)                539
time                      3354
species                   2838
investigator or source      17
pdf                          0
href formula                 1
href                         0
case number.1                0
case number.2                0
original order               0
unnamed: 22               6301
unnamed: 23               6300
dtype: int64

In [22]:
# hp: remove the columns with 40% of missing values (columns NOT relevant for my analysis)
# drop selected columns
drop_cols = list(nulls_cols[nulls_cols > 0.4 * 6302].index)
df = df.drop(drop_cols, axis=1)
df

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,"No injury to occupant, outrigger canoe and pad...",N,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,Minor injury to left thigh,N,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,Injury to left lower leg from surfboard skeg,N,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,Minor injury to lower leg,N,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,Lacerations to leg & hand shark PROVOKED INCIDENT,N,A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,FATAL,Y,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,FATAL,Y,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,FATAL,Y,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,FATAL,Y,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,"FATAL. ""Shark bit him in half, carrying away t...",Y,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0

In [23]:
# let's analyse the others colums to see what's going on
# number of nulls/columns
nulls_cols = df.isnull().sum()
nulls_cols

case_number                 1
date                        0
year                        2
type                        4
country                    50
area                      455
location                  540
activity                  544
name                      210
sex                       565
injury                     28
fatal (y/n)               539
investigator or source     17
pdf                         0
href formula                1
href                        0
case number.1               0
case number.2               0
original order              0
dtype: int64

In [24]:
# INVESTIGATION!

In [25]:
# 'case number'
null_casenumb = df[(df['case_number'].isnull()==True)]
null_casenumb

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
5488,NaN,Reported 06-Sep-1905,1905.0,Provoked,USA,Florida,"Fort Pierce, St Lucie County",Fishing,David Curry,M,Lacerations to leg from hooked shark PROVOKED ...,N,"Muncie Evening Press, 8/6/1913",1905.09.06.R-Curry.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.09.06.R,1905.09.06.R,815.0

In [26]:
# 'CASE_NUMBER'
df.iloc[5486:5491, :]

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
5486,1905.12.29,29-Dec-1905,1905.0,Invalid,AUSTRALIA,Western Australia,Geraldton,Bathing,Hugh Carroll,M,"""Bad wound in the leg"" - 7-ft shark caught in ...",NaN,"The Advertiser, 12/30/1905",1905.12.29-Carroll.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.12.29,1905.12.29,817.0
5487,1905.09.29,29-Sep-1905,1905.0,Unprovoked,AUSTRALIA,New South Wales,"Waverly, Sydney",Swimming,Jame Crotty,M,FATAL. Shark involvement suspected but not con...,Y,"The Argus, 9/30/1905",1905.09.29-Crotty.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.09.29,1905.09.29,816.0
5488,NaN,Reported 06-Sep-1905,1905.0,Provoked,USA,Florida,"Fort Pierce, St Lucie County",Fishing,David Curry,M,Lacerations to leg from hooked shark PROVOKED ...,N,"Muncie Evening Press, 8/6/1913",1905.09.06.R-Curry.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.09.06.R,1905.09.06.R,815.0
5489,1905.08.24,24-Aug-1905,1905.0,Invalid,EGYPT,Suez Canal,Port Said,Human head found in shark caught by British st...,NaN,M,Probable drowning & scavenging.,NaN,"C. Moore, GSAF",1905.08.24-Head-in-shark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.08.24,1905.08.24,814.0
5490,1905.08.00.b,Late Aug-1905,1905.0,Unprovoked,USA,New Jersey,"Atlantic City, Atlantic County",Swimming from naptha launch after a day of fis...,George Wright,M,3 toes of right foot were severed,N,The Sun (undated article),1905.08.00.b-Wright.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.08.00.b,1905.08.00.b,813.0

In [27]:
# changing the missing 'case number' with the date of the attack
df.case_number = df.case_number.fillna('1905.09.06')

In [28]:
# YEAR
null_year = df[(df['year'].isnull()==True)]
null_year

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
187,2017.01.08.R,Reported 08-Jan-2017,NaN,Invalid,AUSTRALIA,Queensland,NaN,Spearfishing,Kerry Daniel,M,"No attack, shark made a threat display",NaN,Liquid Vision 1/8/2017,2017.01.08.R-KerryDaniel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.01.08.R,2017.01.08.R,6116.0
6079,1836.08.19.R,Reported 19-Aug-1836,NaN,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,FATAL,Y,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,224.0

In [29]:
df.year = df.year.fillna(0)

In [30]:
# check the 'year' column data type
df.year.dtype

dtype('float64')

In [31]:
# change from float to int
df.year = df.year.astype(int)
df.year.dtype

dtype('int32')

In [32]:
df.loc[187].replace(0, 2017)
df.loc[6079].replace(0, 1836)

case_number                                                    1836.08.19.R
date                                                   Reported 19-Aug-1836
year                                                                   1836
type                                                             Unprovoked
country                                                             ENGLAND
area                                                             Cumberland
location                                                         Whitehaven
activity                                                           Swimming
name                                                                  a boy
sex                                                                       M
injury                                                                FATAL
fatal (y/n)                                                               Y
investigator or source                                       C. Moore, GSAF
pdf                                             1835.08.19.R-Whitehaven.pdf
href formula              http://sharkattackfile.net/spreadsheets/pdf_di...
href                      http://sharkattackfile.net/spreadsheets/pdf_di...
case number.1                                                  1836.08.19.R
case number.2                                                  1836.08.19.R
original order                                                          224
Name: 6079, dtype: object

In [33]:
# TYPE
null_type = df[(df['type'].isnull()==True)]
# creation a subset with the activity people were doing --> maybe there is a correlation
null_type = null_type[['type','activity']]
null_type

     type           activity
85    NaN            Fishing
382   NaN            Surfing
4867  NaN  Wreck of a sampam
5705  NaN             Diving

In [34]:
# comparing similar activities, it is reasonable to think that all the missing activities are 'Unprovoked'
df.groupby('activity').get_group('Fishing')
df.groupby('activity').get_group('Surfing')
df.groupby('activity').get_group('Diving')
df.groupby('activity').get_group('Wreck of a sampam')

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
4867,1936.09.11.R,Reported 11-Sep-1936,1936,NaN,VIETNAM,NaN,Saigon,Wreck of a sampam,8 crew,M,FATAL,Y,"Lansing State Journal, 9/11/1936",1936.09.11-Saigon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1936.09.11.R,1936.09.11.R,1436.0

In [35]:
# replace missing values with 'Unprovoked'
df.type = df.type.fillna('Unprovoked')

In [36]:
# COUNTRY, AREA, LOCATION
# If the area, the position and the country are null, it is impossible to determine them. --> 'Unknown'
df[(df['country'].isnull()==True) & (df['area'].isnull()==True) & (df['location'].isnull()==True)]

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
62,2017.11.13.R,Reported 13-Nov-2017,2017,Unprovoked,NaN,NaN,NaN,Surfing,Timur Yunusov,M,Puncture wounds to feet,N,Instagram,2017.11.13.R-Timur.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.11.13.R,2017.11.13.R,6241.0
525,2014.08.00,Aug-2014,2014,Invalid,NaN,NaN,NaN,Sea disaster,Cuban refugees,M,Shark involvement prior to death not confirmed,NaN,"Associated Press, 11/27/2014",2014.08.00-Cuban-refugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.08.00,2014.08.00,5778.0
3378,1970.11.00,Nov-1970,1970,Unprovoked,NaN,NaN,NaN,NaN,Heinz Plotsky,M,Extensive injuries,N,"H.D. Baldridge (1994), SAF Case #1645",1970.11.00-NV-Plotsky.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.11.00,1970.11.00,2925.0
3388,1970.07.05,5-Jul-1970,1970,Unprovoked,NaN,NaN,NaN,NaN,male,M,Finger or toe severed,N,"H.D. Baldridge (1994), SAF Case #1628",1970.07.05-NV-male.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.07.05,1970.07.05,2915.0
3395,1970.04.00.b,Apr-1970,1970,Provoked,NaN,NaN,NaN,Freediving,Lionel Jarvis,M,Arm abraded & lacerated. Recorded as PROVOKED ...,N,"H.D. Baldridge (1994), SAF Case #1616",1970.04.00.b-NV-Jarvis.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.04.00.b,1970.04.00.b,2908.0
3399,1970.02.05,5-Feb-1970,1970,Unprovoked,NaN,NaN,NaN,Wading,Sally Anne Irvine,F,Lacerations to lower leg,N,H.D. Baldridge (1994) SAF Case #1626,1970.02.05-NV-Irvine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.02.05,1970.02.05,2904.0
3425,1969.08.00,Aug-1969,1969,Unprovoked,NaN,NaN,NaN,NaN,Rodney Hughes,M,Am lacerated,N,H.D. Baldridge (1994) SAF Case #1602,1969.08.00-NV-Hughes.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1969.08.00,1969.08.00,2878.0
3661,1964.09.27,27-Sep-1964,1964,Invalid,NaN,NaN,NaN,Spearfishing,Giancarlo Griffon,M,"Disappeared, probable drowning but sharks in a...",NaN,C. Moore. GSAF,1964.09.27-Griffon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1964.09.27,1964.09.27,2642.0
4726,1942.00.00.e,1942,1942,Sea Disaster,NaN,NaN,NaN,Jumped overboard from torpedoed Panamanian fre...,male,M,FATAL,Y,"V.M. Coppleson (1962), p.258",1942.00.00.e-seaman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.00.00.e,1942.00.00.e,1577.0
4729,1942.00.00.b,1942,1942,Boating,NaN,NaN,NaN,"Days before the surrender of Singapore, the 3 ...","Bombardier J. Hall, Private Green of the Sherw...",M,No injury to occupants. Sharks continually fol...,N,"V.M. Coppleson (1962), p.206",1942.00.00.b-Hall-Green-Jennings.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.00.00.b,1942.00.00.b,1574.0
4911,1935.04.12.R,Reported 12-Apr-1935,1935,Unprovoked,NaN,NaN,NaN,Diving,Pearl Purdy Scott,F,Laceration to left leg,N,"Port Arthur News, 4/12/1935",1935.04.12.R-PearlPurdyScott.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1935.04.12.R,1935.04.12.R,1392.0
5060,1929.12.09.R,Reported 09-Dec-1929,1929,Unprovoked,NaN,NaN,NaN,NaN,Thomas Duggan,M,FATAL,Y,"The Age, 12/9/1929",1929.12.09.R-Duggan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1929.12.09.R,1929.12.09.R,1243.0
5586,1898.09.19.b.R,Reported 19-Sep-1898,1898,Unprovoked,NaN,NaN,NaN,Diving,Halletts,M,Lacerations to hand from shark trapped inside ...,N,"Lincoln Evening News & Daily Call, 9/19/1898",1898.09.19.b.R-Halletts.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1898.09.19.b.R,1898.09.19.b.R,717.0
5587,1898.09.19.a.R,Reported 19-Sep-1898,1898,Unprovoked,NaN,NaN,NaN,Diving,male,M,Lacerations to fingers,N,"Lincoln Evening News & Daily Call, 9/19/1898",1898.09.19.a.R.Sully.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1898.09.19.a.R,1898.09.19.a.R,716.0
5636,1895.06.13.R,Reported 13-Jun-1895,1895,Unprovoked,NaN,NaN,NaN,Diving,Marsh,M,Right hand severed,N,"Lima Times, 6/13/1895",1895.06.13.R-EnglishDiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1895.06.13.R,1895.06.13.R,667.0
5770,1885.04.16.R,Reported 16-Apr-1885,1885,Unprovoked,NaN,NaN,NaN,Swimming,2 males,M,FATAL,Y,"Gleaner (Jamaica), 4/16/1885",1885.04.16.R-GermanShip.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1885.04.16.R,1885.04.16.R,533.0
5839,1878.10.13,13-Oct-1878,1878,Unprovoked,NaN,NaN,NaN,Jumped overboard after murdering 2 shipmates,Sherrington,M,FATAL,Y,The Maitland Mercury & Hunter River General Ad...,1878.10.13-Sherrington.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1878.10.13,1878.10.13,464.0
5885,1874.06.15.a.R,Reported 15-Jun-1874,1874,Unprovoked,NaN,NaN,NaN,Salvaging a shipwreck,male,M,Heel bitten,N,"Daily Southern Cross, 6/15/1874",1874.06.15.a.R-Achilles-tendon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1874.06.15.a.R,1874.06.15.a.R,418.0
5920,1869.04.10,10-Apr-1869,1869,Invalid,NaN,NaN,NaN,Fell overboard,Christian Frederick,M,FATAL,NaN,"Nelson Examiner & New Zealand Chronicle, 4/24/...",1869.04.10-Frederick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1869.04.10,1869.04.10,383.0
5996,1856.11.20.R,Reported 20-Nov-1856,1856,Unprovoked,NaN,NaN,NaN,Swimming,Cornelius Conhlren,M,FATAL,Y,"Pacific Commercial Advertiser, 11/20/1856",1856.11.20.R-Conhlren.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1856.11.20.R,1856.11.20.R,307.0
6001,1855.07.28,28-Jul-1855,1855,Unprovoked,NaN,NaN,NaN,Bathing,"a young boy, one of the crew of the Post Boy",M,FATAL,Y,"Maitland Mercury, 8/25/1855",1855.07.28-PostBoy-sailors.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1855.07.28,1855.07.28,302.0
6092,1830.04.22.R,Reported 22-Apr-1830,1830,Unprovoked,NaN,NaN,NaN,NaN,Jose,M,FATAL,Y,"The Torchlight & Public Advertiser, 4/22/1830",1830.04.22.R-Jose.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1830.04.22.R,1830.04.22.R,211.0
6119,1811.03.01,01-Mar-1811,1811,Unprovoked,NaN,NaN,NaN,Fell overboard,John Walker,M,FATAL,Y,Journal of Captain Marryat,1811.03.01-John-Walker.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1811.03.01,1811.03.01,184.0
6131,1801.12.18.R,Reported 18-Dec-1801,1801,Provoked,NaN,NaN,NaN,Standing on landed shark's tail,Stephen Pettigew,N,"FATAL, PROVOKED INCIDENT",Y,"The Evening Post, 12/18/1801",1801.12.18.R-Pettigrew.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1801.12.18.R,1801.12.18.R,172.0
6133,1797.05.28.R,Reported May-28-1797,1797,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,FATAL,Y,The Observer 5/28/1797,1797.05.28.R-Cloverdale.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1797.05.28.R,1797.05.28.R,170.0
6165,1638.00.00.R,Reported 1638,1638,Unprovoked,NaN,NaN,NaN,NaN,sailors,M,NaN,UNKNOWN,Sir Thomas Herbert,1638.00.00.R-Herbert,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1638.00.00.R,1638.00.00.R,138.0
6171,1555.00.00,1555,1555,Unprovoked,NaN,NaN,NaN,Swimming,male,M,NaN,UNKNOWN,Olaus Magnus,1555.00.00 - Olaus Magnus.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1555.00.00,1555.00.00,132.0
6199,ND-0124,Before 2011,0,Provoked,NaN,NaN,NaN,NaN,Phillip Peters,M,Bitten by captive sharks PROVOKED INCIDENTS,N,"Watertown Daily Times, 7/8/2011",ND-0124-Peters.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0124,ND-0124,104.0
6259,ND.0044,1941-1945,0,Sea Disaster,NaN,NaN,NaN,A group of survivors on a raft for 17-days,C.,NaN,"FATAL, shark leapt into raft and bit the man w...",Y,"G.A. Llano in Airmen Against the Sea, p.69",ND-0044-C.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0044,ND.0044,44.0

In [37]:
df.loc[(df['country'].isnull()==True) & (df['area'].isnull()==True) & (df['location'].isnull()==True),['country','area','location']] = 'UNKNOWN'

In [38]:
# LOCATION Impossible to know --> 'No location'
null_location = df[(df['location'].isnull()==True)]

In [39]:
df.loc[(df['location'].isnull()==True), ['location']] = 'No Location'

In [40]:
# AREA Impossible to specify it --> 'No area'
null_area = df[(df['area'].isnull()==True)]

In [41]:
df.loc[(df['area'].isnull()==True), ['area']] = 'No Area'

In [42]:
# COUNTRY 
null_country = df[(df['country'].isnull()==True)]
null_country

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
2956,1983.00.00.d,Ca. 1983,1983,Unprovoked,NaN,English Channel,No Location,Swimming,Padma Shri Taranath Narayan Shenoy,M,Left leg bitten,N,"Times of India, 2/5/2012",1983.00.00.d-Shenoy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1983.00.00.d,1983.00.00.d,3347.0
3387,1970.08.02,02-Aug-1970,1970,Invalid,NaN,Caribbean Sea,Between St. Kitts & Nevis,Sea Disaster Sinking of ferryboat Christina,NaN,NaN,"Sharks scavenged on bodies, but no record of t...",NaN,"Rome News Tribune, 8/3/1970",1970.08.02-Christina-ferryboat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.08.02,1970.08.02,2916.0
3605,1965.10.21,21-Oct-1965,1965,Unprovoked,NaN,No Area,Florida Strait,The boat Caribou II sank,Mario Castellanos,M,Survived,N,"Lodi News Sentinel, 10/30/1965",1965.10.21-Castellanos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1965.10.21,1965.10.21,2698.0
4018,1960.01.26,26-Jan-1960,1960,Sea Disaster,NaN,"Between Timor & Darwin, Australia",No Location,Portuguese Airliner with 9 people aboard went ...,NaN,NaN,"As searchers approached wreckage, sharks circl...",N,"V.M. Coppleson (1962), p.260",1960.01.26-Portuguese airliner.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1960.01.26,1960.01.26,2285.0
4231,1956.09.13,13-Sep-1956,1956,Unprovoked,NaN,Near the Andaman & Nicobar Islands,No Location,Climbing back on ship,male,M,FATAL,Y,M. Hosina,1956.09.13-TunaBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1956.09.13,1956.09.13,2072.0
4266,1956.00.00.g,1956,1956,Sea Disaster,NaN,Between Comores & Madagascar,Geyser Bank,Shipwreck,"Captain Eric Hunt, the cook & a French passenger",M,FATAL,Y,dinofish.com,1956.00.00.g-Capt-Hunt.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1956.00.00.g,1956.00.00.g,2037.0
4498,1949.12.00.b,Dec-1949,1949,Sea Disaster,NaN,Caribbean Sea,Between Cuba & Costa Rica,"Sea Disaster, sinking of the motorship Wingate","Albert Battles, James Dean & 4 crew",M,Fatal or drowning or scavenging,Y,"Canberra Times, 1/6/1950",1949.12.00.b-Wingate.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1949.12.00.b,1949.12.00.b,1805.0
4639,1944.10.24,24-Oct-1944,1944,Sea Disaster,NaN,No Area,225 miles east of Hong Kong,Japanese POW ship Arisan Maru with 1800 Americ...,NaN,M,Most of the men drowned & some were taken by s...,Y,internet (multiple),1944.10.24-ArisanMaru.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1944.10.24,1944.10.24,1664.0
4700,1942.11.00.a,Nov-1942,1942,Sea Disaster,NaN,Off South American coast,No Location,Dutch merchant ship Zaandam torpedoed by the ...,NaN,M,FATAL,Y,"M. Murphy; V.M. Coppleson (1962), pp.207-208",1942.11.00.a-Izzi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.11.00.a,1942.11.00.a,1603.0
4712,1942.06.00,Jun-1942,1942,Unprovoked,NaN,300 miles east of St. Thomas (Virgin Islands),No Location,On life raft tethered to lifeboat. A seaman pu...,male,M,Forearm lacerated,N,"V.M. Coppleson (1962), p.258",1942.06.00-on-life-raft.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.06.00,1942.06.00,1591.0
5020,1931.04.27.R,Reported 27-Apr-1931,1931,Unprovoked,NaN,French Southern Territories,Île Saint-Paul,"Fishing, boat capsized",Quillezic,M,FATAL,Y,"Los Angeles Times, 4/27/1931",1931.04.27.R-Quillezic.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1931.04.27.R,1931.04.27.R,1283.0
5425,1909.01.17,17-Jan-1909,1909,Invalid,NaN,No Area,Near the equator,Jumped overboard,Thomas Butler,M,FATAL,NaN,"Star, 3/18/1909",1909.01.17-Butler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1909.01.17,1909.01.17,878.0
5612,1897.03.15.b.R,Reported 15-Mar-1897,1897,Unprovoked,NaN,Mediterranean Sea,No Location,Swimming,male,M,FATAL,Y,"Daily Northwestern, 5/15/1897",1897.03.15.b.R-Mediterranean.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1897.03.15.b.R,1897.03.15.b.R,691.0
5742,1887.07.30,30-Jul-1887,1887,Sea Disaster,NaN,Gulf of California,No Location,"Sea disaster, wreck of the sloop Sara",2 males,M,FATAL,Y,"Austin Weekly Statesman, 8/11/1887",1887.07.30-TheSara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1887.07.30,1887.07.30,561.0
5808,1881.08.16.R,Reported 16-Aug-1881,1881,Unprovoked,NaN,Western Banks,No Location,"Floating, holding onto an oar after dory capsized",George Sedgwick,M,FATAL,Y,"Lewiston Evening Journal, 8/16/1881",1881.08.16.R-Sedgwick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1881.08.16.R,1881.08.16.R,495.0
5810,1881.06.25,25-Jul-1881,1881,Unprovoked,NaN,No Area,Santa Cruz,Bathing,Father Hudson,M,Survived,N,"Grey River Argus,10/3/1881, p.2",1881.06.25-FatherHudson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1881.06.25,1881.06.25,493.0
6137,1787.07.05,05-Jul-1787,1787,Unprovoked,NaN,St Helena,Landing Place,Swimming,Private Isaac Hicksled,M,FATAL,Y,"H.R. Janisch (1885), Extracts from the St. Hel...",1787.07.05-Hicksled.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1787.07.05,1787.07.05,166.0
6155,1742.12.17,17-Dec-1742,1742,Unprovoked,NaN,No Area,Carlisle Bay,Swimming,2 impressed seamen,M,FATAL,Y,"C. Moore, GSAF",1742.12.17-AdviceSeamen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1742.12.17,1742.12.17,148.0
6175,0077.00.00,77 A.D.,77,Unprovoked,NaN,Ionian Sea,No Location,Sponge diving,males,M,FATAL,Y,Perils mentioned by Pliny the Elder (23 A.D. t...,77AD-Pliny.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0077.00.00,0077.00.00,128.0
6177,0000.0214,Ca. 214 B.C.,0,Unprovoked,NaN,Ionian Sea,No Location,Ascending from a dive,"Tharsys, a sponge diver",M,"FATAL, shark/s bit him in two",Y,"Reported by Greek poet, Leonidas of Tarentum (...",214BC-Tharsys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0000.0214,0000.0214,126.0
6206,ND-0114,Before 2012,0,Unprovoked,NaN,No Area,In a river feeding into the Bay of Bengal,Netting shrimp,Sametra Mestri,F,Hand severed,N,National Georgraphic Television,ND-0114-BayOfBengal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0114,ND-0114,97.0

In [43]:
b = df[df['area'] == 'Western Banks']
b

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
5808,1881.08.16.R,Reported 16-Aug-1881,1881,Unprovoked,NaN,Western Banks,No Location,"Floating, holding onto an oar after dory capsized",George Sedgwick,M,FATAL,Y,"Lewiston Evening Journal, 8/16/1881",1881.08.16.R-Sedgwick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1881.08.16.R,1881.08.16.R,495.0

In [44]:
# Mediterranean Sea
df.loc[(df['area']=='Ionian Sea') | (df['area']=='Mediterranean Sea'),'country'] = 'MEDITERRANEAN SEA'

In [45]:
# England
df.loc[(df['area']=='English Channel'),'country'] = 'ENGLAND'

In [46]:
# Central and South America (Cuba-Panama-Colombia) 
df.loc[(df['area']=='Caribbean Sea') | (df['area']=='Off South American coast') | (df['area']=='300 miles east of St. Thomas (Virgin Islands)'),'country'] = 'CENTRAL AND SOUTH AMERICA'

In [47]:
# Australia  
df.loc[(df['area']=='Between Timor & Darwin, Australia'),'country'] = 'AUSTRALIA'

In [48]:
# Thailand 
df.loc[(df['area']=='Near the Andaman & Nicobar Islands'),'country'] = 'THAILAND'

In [49]:
# Africa
df.loc[(df['area']=='Between Comores & Madagascar'),'country'] = 'AFRICA'

In [50]:
# Antarctic
df.loc[(df['area']=='French Southern Territories'),'country'] = 'ANTARCTIC'

In [51]:
# USA
df.loc[(df['area']=='Gulf of California'),'country'] = 'USA'

In [52]:
# Atlantic Ocean
df.loc[(df['area']=='St Helena'),'country'] = 'MID ATLANTIC OCEAN'

In [53]:
# Other
df.loc[(df['area']=='No Area') | (df['area']=='Western Banks'),'country'] = 'UNKNOWN'

In [54]:
# df['country'].unique()

In [55]:
# bucle? npwhere?

In [56]:
# NAME & SEX
# If the name or the sex are null, it is impossible to determine them --> 'Unknown'
df[(df['name'].isnull()==True) & (df['sex'].isnull()==True)]

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
32,2018.04.09,09-Apr-2018,2018,Unprovoked,UNKNOWN,No Area,"Magenta Beach, Noumea",Windsurfing,NaN,NaN,"No injury, shark bit board",N,"Les Nouvelles Caledoniennes, 4/10/2018",2018.04.09-Magenta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.09,2018.04.09,6271.0
86,2017.09.14,Sep-2017,2017,Boating,AUSTRALIA,Westerm Australia,Esperance,Fishing,NaN,NaN,"sharks rammed boats, no injury to occupants",N,"B. Myatt, GSAF",2017.09.14-EsperanceBoats.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.14,2017.09.14,6217.0
124,2017.07.02,02-Jul-2017,2017,Invalid,COMOROS,Anjouan,Moya,Fishing,NaN,NaN,"Skull found in shark, a probable drowning & sc...",NaN,"Linfo, 7/3/2017",2017.07.02-Comoros.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.02,2017.07.02,6179.0
154,2017.04.17.b,17-Apr-2017,2017,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",NaN,NaN,NaN,Minor bite to the foot,N,"Daytona Beach News-Journal, 4/17/2017",2017.04.17.b-Volusia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.04.17.b,2017.04.17.b,6149.0
226,2016.09.00,Sep-2016,2016,Invalid,UNKNOWN,No Area,Guadalupe Island,Cage Diving,NaN,NaN,"No injury to divers, white shark breached cage",NaN,K. Yonker,2016.09.00-Breach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.00,2016.09.00,6077.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6157,1733.00.00,1733,1733,Invalid,ICELAND,Bardestrand,Talkknefiord,NaN,NaN,NaN,"Partial hominid remains recovered from shark, ...",NaN,E. Olafsen,1733.00.00-Iceland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1733.00.00,1733.00.00,146.0
6185,ND-0150,Before 1934,0,Unprovoked,URUGUAY,Rocha,"Isla Chica, La Paloma",Swimming,NaN,NaN,Foot bitten,N,"Di Candia, 2004",ND-0150-Uruguay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0150,ND-0150,118.0
6197,ND-0129,Before 2012,0,Unprovoked,SPAIN,Canary Islands,Tenerife,Skin diving,NaN,NaN,Injury required 16 stitches,N,"C. Moore, GSAF",ND-0129-Tenerife.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0129,ND-0129,106.0
6237,ND.0073,"No date, Before 1963",0,Unprovoked,UNKNOWN,No Area,"Keppel Harbor, 2 miles from Singapore city ce...",Swimming,NaN,NaN,Recovered,N,"V.M. Coppleson (1958), p.266",ND-0073-KeppelHarbourSingapore.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0073,ND.0073,66.0
6278,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Barachois,Swimming,NaN,NaN,FATAL,Y,G. Van Grevelynghe,ND-0024-Barachois-Reunion.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0024,ND.0024,25.0

In [57]:
df.loc[(df['name'].isnull()==True) | (df['sex'].isnull()==True),['name','sex']] = 'Unknown'

In [58]:
# SEX
# check!
# null_sex = df[(df['sex'].isnull()==True)]
# null_sex['name'].unique()

In [59]:
# ACTIVITY, FATAL & INJURY
# If the activity, the injury and the gravity of the attack are unknown, this cases are not relevant. We can drop them.
df[(df['activity'].isnull()==True) & (df['fatal (y/n)'].isnull()==True) & (df['injury'].isnull()==True)]

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
5370,1912.05.04,04-May-1912,1912,Invalid,SOUTH AFRICA,KwaZulu-Natal,Durban,NaN,arm recovered from hooked shark,M,NaN,NaN,"M. Levine, GSAF",1912.05.04-arm.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1912.05.04,1912.05.04,933.0
5965,1862.12.04,04-Dec-1862,1862,Invalid,NEW ZEALAND,South Island,Lyttleton?,NaN,Unknown,Unknown,NaN,NaN,"Bendigo Advertiser, 1/3/1863",1862.12.04-Lyttleton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1862.12.04,1862.12.04,338.0

In [60]:
df.drop([5370,5965], axis= 0)
df.head(3)

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,"No injury to occupant, outrigger canoe and pad...",N,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,Minor injury to left thigh,N,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,Injury to left lower leg from surfboard skeg,N,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0

In [61]:
# FATAL & INJURY
# If we don't have information about injuries/fatal attacks, it is impossible to determine them --> 'Unknown'
df[(df['fatal (y/n)'].isnull()==True) & (df['injury'].isnull()==True)]

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
1366,2007.07.00,Jul-2007,2007,Invalid,UNKNOWN,No Area,No Location,Murder,Unknown,Unknown,NaN,NaN,"Daily Guide, 8/20/2007",2007.07.00-Takyi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.07.00,2007.07.00,4937.0
3207,1975.10.04,04-Oct-1975,1975,Invalid,USA,California,"Seal Beach, Orange County",Surfing,Unknown,Unknown,NaN,NaN,Unconfirmed Report,1975.10.04-NV-California.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.10.04,1975.10.04,3096.0
3457,1968.09.22,22-Sep-1968,1968,Invalid,USA,Florida,"Riviera Beach, Palm Beach County",Surfing,Unknown,Unknown,NaN,NaN,"M. Vorenberg, GSAF",1968.09.22-NV-RivieraBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1968.09.22,1968.09.22,2846.0
3491,1968.00.00.a,1968,1968,Invalid,USA,Florida,"Jensen Beach, Martin County",Surfing,Unknown,Unknown,NaN,NaN,Unverified,1968.00.00.a-NV-JensenBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1968.00.00.a,1968.00.00.a,2812.0
5370,1912.05.04,04-May-1912,1912,Invalid,SOUTH AFRICA,KwaZulu-Natal,Durban,NaN,arm recovered from hooked shark,M,NaN,NaN,"M. Levine, GSAF",1912.05.04-arm.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1912.05.04,1912.05.04,933.0
5547,1901.06.29.R,Reported 29-Jun-1901,1901,Invalid,YEMEN,Aden,No Location,Diving around anchored liner,boy,M,NaN,NaN,"The Graphic, 6/29/1901",1901.06.29.R-Aden.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1901.06.29.R,1901.06.29.R,756.0
5965,1862.12.04,04-Dec-1862,1862,Invalid,NEW ZEALAND,South Island,Lyttleton?,NaN,Unknown,Unknown,NaN,NaN,"Bendigo Advertiser, 1/3/1863",1862.12.04-Lyttleton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1862.12.04,1862.12.04,338.0

In [62]:
df.loc[(df['injury'].isnull()==True) | (df['fatal (y/n)'].isnull()==True),['injury','fatal (y/n)']] = 'Unknown'

In [63]:
# ACTIVITY & INJURY
# If we don't have information about injuries/fatal attacks, it is impossible to determine them --> 'Unknown'
df[(df['activity'].isnull()==True) | (df['injury'].isnull()==True)]

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
47,2018.01.28,28-Jan-2018,2018,Unprovoked,AUSTRALIA,Western Australia,Cone Bay,NaN,male,M,Injuries to right leg,N,"ABC.net.au, 01/28/2018",2018.01.28-ConeBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.01.28,2018.01.28,6256.0
108,2017.07.29.a,29-Jul-2017,2017,Unprovoked,USA,South Carolina,"DeBordieu Colony, Georgetown County",NaN,female x 2,F,Bite to left thigh / minor injury,N,"C. Creswell, GSAF",2017.07.29.a-Georgetown.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.29.a,2017.07.29.a,6195.0
112,2017.07.23.b,23-Jul-2017,2017,Unprovoked,USA,New Jersey,Ventnor,NaN,Isabella Smith,F,Minor injury to hand,N,A. Smith,2017.07.23.b-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.23.b,2017.07.23.b,6191.0
114,2017.07.22,22-Jul-2017,2017,Unprovoked,USA,Florida,"Snipes Point, Monroe County",NaN,female,F,Foot bitten,N,"NBC Miami, 7/23/2017",2017.07.22-Keys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.22,2017.07.22,6189.0
154,2017.04.17.b,17-Apr-2017,2017,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",NaN,Unknown,Unknown,Minor bite to the foot,N,"Daytona Beach News-Journal, 4/17/2017",2017.04.17.b-Volusia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.04.17.b,2017.04.17.b,6149.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6269,ND.0034,1940-1946,0,Sea Disaster,UNKNOWN,No Area,No Location,NaN,"8 US airmen in the water, 1 was bitten by a shark",M,FATAL,Y,G. Llano,ND-0034-8-men-on-raft.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0034,ND.0034,34.0
6277,ND.0025,Before 1927,0,Unprovoked,AUSTRALIA,New South Wales,"Spectacle Island, Port Jackson",NaN,"male, the Sergeant of Marines",M,Unknown,Unknown,H. Capper,ND-0025-Sgt-SpectacleIsland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0025,ND.0025,26.0
6282,ND.0020,1920 -1923,0,Unprovoked,AUSTRALIA,Queensland,Great Barrier Reef,NaN,3 Japanese divers,M,FATAL,Y,"V.M. Coppleson (1958), p.241",ND-0020-3JapaneseDivers.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0020,ND.0020,21.0
6292,ND.0010,Circa 1862,0,Unprovoked,USA,Hawaii,Puna,NaN,"A ""chiefess""",F,Ankle bitten,N,Captain W. Young,ND-0010-Puna Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0010,ND.0010,11.0
6300,ND.0002,1883-1889,0,Unprovoked,UNKNOWN,No Area,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,FATAL,Y,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0

In [64]:
null_injury = df[(df['activity'].isnull()==True)]
# null_injury['injury'].unique()

In [65]:
# ACTIVITY
# It is quite difficult to determine precisely the type of activity although it is not impossible
# In this case I will put all the parameters as 'Unknown' to focus on other aspects of the problem, aware that this point could be deepened
null_activity = df[(df['activity'].isnull()==True)]
null_activity

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
47,2018.01.28,28-Jan-2018,2018,Unprovoked,AUSTRALIA,Western Australia,Cone Bay,NaN,male,M,Injuries to right leg,N,"ABC.net.au, 01/28/2018",2018.01.28-ConeBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.01.28,2018.01.28,6256.0
108,2017.07.29.a,29-Jul-2017,2017,Unprovoked,USA,South Carolina,"DeBordieu Colony, Georgetown County",NaN,female x 2,F,Bite to left thigh / minor injury,N,"C. Creswell, GSAF",2017.07.29.a-Georgetown.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.29.a,2017.07.29.a,6195.0
112,2017.07.23.b,23-Jul-2017,2017,Unprovoked,USA,New Jersey,Ventnor,NaN,Isabella Smith,F,Minor injury to hand,N,A. Smith,2017.07.23.b-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.23.b,2017.07.23.b,6191.0
114,2017.07.22,22-Jul-2017,2017,Unprovoked,USA,Florida,"Snipes Point, Monroe County",NaN,female,F,Foot bitten,N,"NBC Miami, 7/23/2017",2017.07.22-Keys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.22,2017.07.22,6189.0
154,2017.04.17.b,17-Apr-2017,2017,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",NaN,Unknown,Unknown,Minor bite to the foot,N,"Daytona Beach News-Journal, 4/17/2017",2017.04.17.b-Volusia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.04.17.b,2017.04.17.b,6149.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6269,ND.0034,1940-1946,0,Sea Disaster,UNKNOWN,No Area,No Location,NaN,"8 US airmen in the water, 1 was bitten by a shark",M,FATAL,Y,G. Llano,ND-0034-8-men-on-raft.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0034,ND.0034,34.0
6277,ND.0025,Before 1927,0,Unprovoked,AUSTRALIA,New South Wales,"Spectacle Island, Port Jackson",NaN,"male, the Sergeant of Marines",M,Unknown,Unknown,H. Capper,ND-0025-Sgt-SpectacleIsland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0025,ND.0025,26.0
6282,ND.0020,1920 -1923,0,Unprovoked,AUSTRALIA,Queensland,Great Barrier Reef,NaN,3 Japanese divers,M,FATAL,Y,"V.M. Coppleson (1958), p.241",ND-0020-3JapaneseDivers.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0020,ND.0020,21.0
6292,ND.0010,Circa 1862,0,Unprovoked,USA,Hawaii,Puna,NaN,"A ""chiefess""",F,Ankle bitten,N,Captain W. Young,ND-0010-Puna Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0010,ND.0010,11.0
6300,ND.0002,1883-1889,0,Unprovoked,UNKNOWN,No Area,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,FATAL,Y,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0

In [66]:
df.loc[(df['activity'].isnull()==True)] = 'Unknown'

In [67]:
# INVESTIGATOR OR SOURCE
# I don't think data of this column are not so relevant... I'll replace nulls with a 'Unknown' (because all the other sources are known)
null_inv = df[(df['investigator or source'].isnull()==True)]

In [68]:
investigators = df['investigator or source'].unique().tolist()

for name in investigators:
    if name != 'Unknown':
        print(f'The investigator/souce is known')
        break
    else:
        print(f'Unknown')

The investigator/souce is known

In [69]:
# replace 0 with 'Unknown'
df['investigator or source'] = df['investigator or source'].fillna('Unknown')

In [70]:
# HREF FORMULA
# like above
null_hrefform = df[(df['href formula'].isnull()==True)]
null_hrefform

,case_number,date,year,type,country,area,location,activity,name,sex,injury,fatal (y/n),investigator or source,pdf,href formula,href,case number.1,case number.2,original order
3244,1975.01.19,19-Jan-1975,1975,Unprovoked,AUSTRALIA,South Australia,Coffin Bay,Surfing,David Barrowman,M,"FATAL, body not recovered",Y,"J. West; Adelaide Advertiser, 1/20/1975; P. Ke...",1975.01.19-Barrowman.pdf,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.01.19,1975.01.19,3059

In [71]:
# df.iloc[3243:3246, :]

In [72]:
df['href formula'] = df['href formula'].fillna(0)

In [73]:
nulls_cols = df.isnull().sum()
nulls_cols

case_number               0
date                      0
year                      0
type                      0
country                   0
area                      0
location                  0
activity                  0
name                      0
sex                       0
injury                    0
fatal (y/n)               0
investigator or source    0
pdf                       0
href formula              0
href                      0
case number.1             0
case number.2             0
original order            0
dtype: int64

### Final Summary ###

In [74]:
# summary
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6302 entries, 0 to 6301
Data columns (total 19 columns):
case_number               6302 non-null object
date                      6302 non-null object
year                      6302 non-null object
type                      6302 non-null object
country                   6302 non-null object
area                      6302 non-null object
location                  6302 non-null object
activity                  6302 non-null object
name                      6302 non-null object
sex                       6302 non-null object
injury                    6302 non-null object
fatal (y/n)               6302 non-null object
investigator or source    6302 non-null object
pdf                       6302 non-null object
href formula              6302 non-null object
href                      6302 non-null object
case number.1             6302 non-null object
case number.2             6302 non-null object
original order            6302 non-null object
dtypes: object(19)
memory usage: 1.1+ MB

In [75]:
# At this point, a good practice is to save the reduced file 'attacks-reduced.csv' for consulting it, if necessary.
df.to_csv('input/attacks-reduced.csv')

## Analysis

In [76]:
# selection of the columns to use in the analysis
# df = df[['case_number','date','year','type','country','area','activity','sex','injury','fatal (y/n)']]
# df.head()